// Loader

export const API_CONFIGURATIONS = 'API_CONFIGURATIONS'
export const LOAD_START = 'LOAD_START'
export const UPDATE_PROGRESS = 'UPDATE_PROGRESS'
export const LOAD_COMPLETE = 'LOAD_COMPLETE'
export const NEW_API = 'NEW_API'
export const NEW_OPERATION = 'NEW_OPERATION'
export const NEW_DEFINITION = 'NEW_DEFINITION'
